config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tweets#index'
    root to: "home#index"
  resources :tweets  do 
    collection do
      get 'search'
    end
    resources :comments ,only: [:create,:edit,:update,:destroy]
  end   
  resources :users,only: [:show,:edit,:update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :tweet               #tweetsテーブルとのアソシエーション
  belongs_to :user                #usersテーブルとのアソシエーション
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
  has_many :comments   
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :tweets
  has_many :comments   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
     comment = Comment.create(text: comment_params[:text], tweet_id: comment_params[:tweet_id], user_id: current_user.id)
    redirect_to "/tweets/#{comment.tweet.id}"
    end
    
    def destroy
        comment = Comment.find(params[:id])
      if comment.user_id == current_user.id
        comment.destroy 
      end
      
    end
    def edit
        @comments = Comment.find(params[:id])
    end
    def update
        @comment = Comment.find(params[:id])
        if @comment.user_id == current_user.id
          @comment.update
        end
    end

  private
  def comment_params
    params.permit(:text, :tweet_id)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

    def index
          @tweets = Tweet.order("created_at DESC").page(params[:page]).per(10)
    end
    
    def new
    end
    
    def create
        Tweet.create( text: tweet_params[:text], user_id: current_user.id)
    end
    def show
        
        @tweet = Tweet.find(params[:id])
        @comments = @tweet.comments.includes(:user).order("created_at DESC").page(params[:page]).per(10)
    end
    def edit
        @tweet = Tweet.find(params[:id])
    end
     
    def destroy
    tweet = Tweet.find(params[:id])
      if tweet.user_id == current_user.id
        tweet.destroy 
      end
    end
    
    def update
    tweet = Tweet.find(params[:id])
    if tweet.user_id == current_user.id
      tweet.update(tweet_params)
    end
    end
    def search
    @tweet = Tweet.where('text LIKE(?)', "%#{params[:search]}%").order("created_at DESC").page(params[:page]).per(10)
    end

    private
    def  tweet_params
        params.permit(:text)
    end
    
    
    
     def move_to_index
         redirect_to action: :index unless user_signed_in?
     end
     
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
         @tweets = Tweet.where(user_id: current_user.id).order("created_at DESC").page(params[:page]).per(10)
    end
    
  def edit
  end

  def update
      current_user.update(update_params)
  end
  private
  def update_params
    params.permit(:nickname)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<div class = space></div>
<h3>
     投稿が完了しました。
</h3>
<a href="/tweets">投稿一覧へ戻る</a>

app/views/comments/destroy.html.erb
    <div class = space></div>
    <h3>
      削除が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>

app/views/comments/edit.html.erb
<div class = space></div>
 <%= form_tag("/tweets/#{@tweet.id}/comments/#{@comment.id}/edit", method: :patch ) do %>
 <div class = las>
    <h3>
      編集する
    </h3>
    <textarea name="text" placeholder="text" rows="10" cols="30"><%= @comments.text %></textarea>
    <input type="submit" value="SEND">
    </div>
  <% end %>

app/views/comments/update.html.erb
<div class = space></div>
<h3>
      更新が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>talkle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel=”icon” type=”image/png” href=“/image/t-logo.png”>
  </head>
  <header class = header>
<h1><%=link_to "talkle",root_path,method: :get%></h1>
<%= form_tag(search_tweets_path,:method => 'get') do %>
  <%= text_field_tag :search %>
  <%= submit_tag 'Search', :name => nil %>
<% end %>
<% if user_signed_in? %>  
          <div class="btn btn--orange btn--radius">
             <%= link_to "マイページ", user_path(current_user) %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            <%= link_to "投稿する", "/tweets/new", class: "post" %>
          </div>
        <% else %>
          <div class="btn btn--orange btn--radius">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
</header>

  <body class=view>
  <div class = space></div>
    <%= yield %>
  </body>
</html>

app/views/tweets/create.html.erb
<div class = space></div>
<h3>
     投稿が完了しました。
</h3>
<a href="/tweets">投稿一覧へ戻る</a>

app/views/tweets/destroy.html.erb
    <div class = space></div>
    <h3>
      削除が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>

app/views/tweets/edit.html.erb
 <div class = space></div>
 <%= form_tag("/tweets/#{@tweet.id}", method: :patch ) do %>
 <div class = las>
    <h3>
      編集する
    </h3>
    <textarea name="text" placeholder="text"rows="10" cols="30"><%= @tweet.text %></textarea>
    <input type="submit" value="SEND">
    </div>
  <% end %>

app/views/tweets/index.html.erb
  <span><% @tweets.each do |tweet| %></span>
  <div class = tweet>
      <div class =write >
        <p><%= tweet.user.nickname%>---<%= tweet.created_at%></p>
        <p><%= tweet.text %>---<%= link_to 'コメント', "/tweets/#{tweet.id}", method: :get %></p>
    </div>

           <% if user_signed_in? && current_user.id == tweet.user_id %>
              <div class = menu>
               <ul>
                <li>
                   <%= link_to '削除', "/tweets/#{tweet.id}", method: :delete %>
                </li>
                <li>
                  <%= link_to '編集', "/tweets/#{tweet.id}/edit", method: :get %>
                </li>
              </ul>
              </div>
           <% end %>
    </div>
  <span><% end %></span>
  <%= paginate(@tweets) %>
  

  

app/views/tweets/new.html.erb
<div class = space></div>
 <%= form_tag('/tweets', method: :post) do %>
    <h3>
      投稿する
    </h3>
    <textarea name="text" placeholder="text"rows="10" cols="30"></textarea>
    <input type="submit" value="SEND">
  <% end %>

app/views/tweets/search.html.erb
<% @tweet.each do |tweet|%>
<div class = tweet>
      <div class =write >
        <p><%= tweet.user.nickname%>---<%= tweet.created_at%></p>
        <p><%= tweet.text %>--- <%= link_to '詳細', "/tweets/#{tweet.id}", method: :get %></p>
    </div>

           <% if user_signed_in? && current_user.id == tweet.user_id %>
              <div class = menu>
               <ul>
                <li>
                   <%= link_to '削除', "/tweets/#{tweet.id}", method: :delete %>
                </li>
                <li>
                  <%= link_to '編集', "/tweets/#{tweet.id}/edit", method: :get %>
                </li>
              </ul>
              </div>
           <% end %>
    </div>
  <span><% end %></span>
  <%= paginate(@tweet) %>
  

app/views/tweets/show.html.erb
  <div class = tweet>
      <div class =write >
        <p><%= @tweet.user.nickname %>---<%= @tweet.created_at%></p>
        <p><%= @tweet.text %></p>
    </div>
    </div>
     <h4>＜コメント一覧＞</h4>
   <div class = tweet>
  <h4>コメントする</h4>
   <% if current_user %>
      <%= form_tag("/tweets/#{@tweet.id}/comments", method: :post) do %>
        <textarea name="text" placeholder="コメントする" ></textarea>
        <input type="submit" value="SEND">
      <% end %>
    <% end %>
</div>
 

        <% @comments.each do |comment| %>
 <div class = tweet>
      <div class =write >
        <p><%= comment.user.nickname%>---<%= comment.created_at%></p>
        <p><%= comment.text %></p>
    </div>

           <% if user_signed_in? && current_user.id == comment.user_id %>
              <div class = menu>
               <ul>
                <li>
                   <%= link_to '削除', "/tweets/#{@tweet.id}/comments/#{comment.id}", method: :delete %>
                </li>
                <li>
                  <% link_to '編集', "/tweets/#{@tweet.id}/comments/#{comment.id}/edit", method: :get %>
                </li>
              </ul>
              </div>
           <% end %>
    </div>
  <span><% end %></span>
 <%= paginate(@comments) %>

app/views/tweets/update.html.erb
<div class = space></div>
<h3>
      更新が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>

app/views/users/edit.html.erb
<%= form_tag("/users/#{current_user.id}", method: :patch ) do %>
 <div class = las>
    <h3>
      編集する
    </h3>
    <textarea name="string" placeholder="nicname"rows="1" cols="6"><%= current_user.nickname %></textarea>
    
    <input type="submit" value="SEND">
    </div>
  <% end %>

app/views/users/show.html.erb
<H3><%=current_user.nickname%>---<%= link_to '編集', "/users/#{current_user.id}/edit", method: :get %></h3>
 <span><% @tweets.each do |tweet| %></span>
  <div class = tweet>
      <div class =write >
        <p><%= current_user.nickname %>---<%= tweet.created_at%></p>
        <p><%= tweet.text %>---<%link_to '詳細', "/tweets/#{tweet.id}", mehod: :get%></p>
    </div>

           <% if user_signed_in? && current_user.id == tweet.user_id %>
              <div class = menu>
               <ul>
                <li>
                   <%= link_to '削除', "/tweets/#{tweet.id}", method: :delete %>
                </li>
                <li>
                  <%= link_to '編集', "/tweets/#{tweet.id}/edit", method: :get %>
                </li>
              </ul>
              </div>
           <% end %>
    </div>
  <span><% end %></span>
  <%= paginate(@tweets) %>
  

app/views/users/update.html.erb
<h3>プロフィールの編集が完了しました。</h3>
    <%= link_to "ホームに戻る", root_path %>